remote_theme: just-the-docs/just-the-docs

title: XR Performance
description: This is a site to organize materials for our class on XR Performance.

markdown: GFM

plugins:
  - jemoji

# Aux links for the upper right navigation
aux_links:
  "XR Studio Guides on GitHub":
    - "https://github.com/lsuxrstudio/xrperformance"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/lsuxrstudio/xrperformance" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
